# Generated by Django 2.0.3 on 2018-03-20 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('remote_addr', models.CharField(max_length=400)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Message privé',
                'verbose_name_plural': 'Message privés',
            },
        ),
    ]
